update test and static actions

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -5,18 +5,46 @@ on: push
 jobs:
   call-secrets-analysis-workflow:
     # Docs: https://github.com/ASFHyP3/actions
-    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.21.0
+    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.21.1
     permissions:
       contents: read
 
-  call-ruff-workflow:
-    # Docs: https://github.com/ASFHyP3/actions
-    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@v0.21.0
+  check-with-ruff:
+    runs-on: ubuntu-24.04-arm
     permissions:
       contents: read
+    steps:
+      - uses: actions/checkout@v7
 
-  call-mypy-workflow:
-    # Docs: https://github.com/ASFHyP3/actions
-    uses: ASFHyP3/actions/.github/workflows/reusable-mypy.yml@v0.21.0
+      - uses: prefix-dev/setup-pixi@v0.10.0
+        with:
+          activate-environment: true
+
+      - name: ruff check
+        run: |
+          ruff check --output-format=github || (echo 'Run `ruff check --fix` to automatically fix errors where possible.' && exit 1)
+
+      - name: ruff format
+        if: ${{ !cancelled() }}
+        run: |
+          ruff format --diff || (echo 'Run `ruff format` to automatically re-format.' && exit 1)
+
+
+  check-with-mypy:
+    runs-on: ubuntu-24.04-arm
     permissions:
       contents: read
+    steps:
+      - uses: actions/checkout@v7
+
+      - uses: prefix-dev/setup-pixi@v0.10.0
+        with:
+          activate-environment: true
+
+      - name: Run pixi install task
+        run: |
+          pixi run install-editable
+
+      - name: Check with MyPy
+        run: |
+          mkdir .mypy_cache && mypy .
